### ISSUE TITLE
Add a project

### ISSUE THREAD

**Issue by Ayeshashaik759** [vinayskywalker/Hactoberfest2022#348]
Hey, vinay I want to contribute to the project folder by creating snake game. Can you assign me this issue.

**Comment by AjayMaheshwari23** [comment]
Hello , I want to add my covid related  project website int this , can you assign me this issue .

**Comment by beastvarun** [comment]
I have a project in C language, which helps new programmers in building logic by solving problems divided in two levels(easy,medium). can i add?
