### ISSUE TITLE
Add leetcode medium question

### ISSUE THREAD

**Issue by khushimarothi** [vinayskywalker/Hactoberfest2022#355]
I want to add leetcode math medium problem .
please assign it for hacktoberfest2022.

**Comment by AjayMaheshwari23** [comment]
I want to add some questions , can you assign it to me .

**Comment by khushimarothi** [comment]
> I want to add some questions , can you assign it to me .

Are you kidding me...

**Comment by khushimarothi** [comment]
@vinayskywalker is this repo a part of hacktoberfest??
